name: Java CI

on: [push]

jobs:
  test-oncokb-endpoint:
    runs-on: ubuntu-latest
    steps:
    - name: GET oncokb data
      env:
        ONCOKB_TOKEN: ${{ secrets.ONCOKB_TOKEN }}
        OK_RESPONSE_CODE: 200
      run: |
        curl -X GET --header 'Accept: application/json' 'https://www.genomenexus.org/annotation/17%3Ag.41242962_41242963insGA?token=$ONCOKB_TOKEN&fields=oncokb' -w ",http_code:%{http_code}"> curl_response.txt
        RESPONSE_CODE=`cat curl_response.txt`
        SEARCH_HTTP_CODE="http_code:200"
        # change to SEARCH_ONCOKB="oncokb" after update database
        SEARCH_ONCOKB="protein_id"
        FILE="curl_response.txt"
        if [ `grep -q "$SEARCH_HTTP_CODE" "$FILE"` -a `grep -q "$SEARCH_ONCOKB" "$FILE"`]
        then
          echo "Request succeeded with expected response"
          exit 0
        else
          echo "Request failed"
          exit 1
        fi

