name: Java CI

on: [push]

jobs:
  test-oncokb-endpoint:
    runs-on: ubuntu-latest
    steps:
    - name: GET oncokb data
      env:
        ONCOKB_TOKEN: ${{ secrets.ONCOKB_TOKEN }}
      run: |
        curl -X GET --header 'Accept: application/json' 'http://www.genomenexus.org/annotation/17%3Ag.41242962_41242963insGA'  -w ",http_code:%{http_code}"> curl.out
        if grep -q 'http_code:200' "$curl.out" ; then
          echo "Request succeeded with expected response"
          exit 0
        else
          echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
          exit 1
        fi

