name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  test-oncokb-endpoint:
    runs-on: ubuntu-latest
    steps:
    - name: GET oncokb data
      env:
        ONCOKB_TOKEN: ${{ secrets.ONCOKB_TOKEN }}
      run: |
        curl -X GET --header 'Accept: application/json' 'http://localhost:38080/annotation/17%3Ag.41242962_41242963insGA'
        RESPONSE_CODE=`cat curl.out`
        if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
        echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
          exit 1
        else
          echo "Request succeeded with expected response code '$OK_RESPONSE_CODE'"
          exit 0
        fi

