name: Java CI

on: [push]

jobs:
  test-oncokb-endpoint:
    runs-on: ubuntu-latest
    steps:
    - name: GET oncokb data
      env:
        ONCOKB_TOKEN: ${{ secrets.ONCOKB_TOKEN }}
        OK_RESPONSE_CODE: 200
      run: |
        curl -X GET --header 'Accept: application/json' 'http://www.genomenexus.org/annotation/17%3Ag.41242962_41242963insGA'  -w ",http_code:%{http_code}"> curl.out
        RESPONSE_CODE=`cat curl.out`
        echo curl.out
        if [[ 'grep 'http_code:400' curl.out' ]]; then
          echo "Request succeeded with expected response code '$OK_RESPONSE_CODE'"
          exit 0
        else
          echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
          exit 1
        fi

